from .search import SearchPageView
from .home import HomePageView
from .about import AboutPageView
from .policies import PolicyPageView
from .contactus import ContactUsFormView
from .history import HistoryPageView
from .watch_later import WatchLaterPageView
from .liked_videos import LikedPageView
from .upload_video import UploadPageView
from .edit_video import EditVideoPageView
from .my_videos import MyVideosView
from .channel import ChannelView
from .playlist import PlaylistView
