# Generated by Django 3.2.5 on 2021-09-10 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import video.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_alter_report_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='crawledvideo',
            options={'verbose_name': 'Crawled video', 'verbose_name_plural': 'Crawled videos'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterModelOptions(
            name='watchlater',
            options={'verbose_name': 'Watch later'},
        ),
        migrations.AddField(
            model_name='video',
            name='is_m3u8_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='video.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.IntegerField(choices=[(1, 'هرزنامه ها'), (3, 'محتوای جنسی'), (5, 'اعمال مضر یا خطرناک'), (6, 'کودک آزاری'), (7, 'تروریسم را ترویج می دهد'), (13, 'اطلاعات غلط'), (15, 'نقض مالکیت معنوی'), (18, 'توهین به قومیت ها یا نژادپرستی'), (20, 'عدم تطابق عنوان و توضیحات با محتوای فیلم'), (22, 'سایر')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='video.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='video.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.channel', verbose_name='Video|Channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'wmv', 'avi', 'flv', 'mkv']), video.utils.validators.FileSizeValidator(max_size=10737418240)], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='video.playlist', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist_order',
            field=models.IntegerField(blank=True, help_text='The order in the playlist could not exceed its size.', null=True, verbose_name='playlist order'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.crawledvideo', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='video.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), video.utils.validators.FileSizeValidator(max_size=512000)], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video|Title'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_laters', to='video.video', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='watched_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Watched at'),
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('1080p', '1080p'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p')], max_length=5, verbose_name='quality')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_formates', to='video.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video format',
                'verbose_name_plural': 'Video formats',
            },
        ),
    ]
