# Generated by Django 3.2.5 on 2021-09-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20210910_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoformat',
            name='quality',
            field=models.CharField(choices=[('1080p', '1080p'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p')], max_length=10, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='videoformat',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_formats', to='video.video', verbose_name='Video'),
        ),
    ]
