# Generated by Django 3.2.5 on 2021-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20210912_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistvideorelation',
            name='order',
            field=models.IntegerField(verbose_name='Playlist order'),
        ),
    ]
