# Generated by Django 3.2.5 on 2021-09-14 05:31

import django.core.validators
from django.db import migrations, models
import video.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_playlistvideorelation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video/posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), video.utils.validators.FileSizeValidator(max_size=5120000)], verbose_name='Poster'),
        ),
    ]
