# Generated by Django 3.2.5 on 2021-09-14 09:45

from django.db import migrations, models
import video.utils.video_code


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_playlistvideorelation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='code',
            field=models.CharField(default=video.utils.video_code.generate_playlist_code, max_length=8, unique=True),
        ),
    ]
