# Generated by Django 3.2.5 on 2021-09-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_playlist_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
