# Generated by Django 3.2.5 on 2021-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('USER', 'USER')], default='USER', max_length=8, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=8, verbose_name='privacy'),
        ),
    ]
