# Generated by Django 3.2.5 on 2021-09-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_poster'),
        ('video', '0012_auto_20210914_1836'),
    ]

    operations = [
    ]
