# Generated by Django 3.2.5 on 2021-09-25 12:33

from django.db import migrations, models
import video.utils.video_code


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20210925_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default=video.utils.video_code.generate_channel_code, max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
