# Generated by Django 3.2.5 on 2021-10-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_contactus'),
        ('video', '0016_alter_channel_name'),
    ]

    operations = [
    ]
