# Generated by Django 3.2.5 on 2021-10-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_rename_is_m3u8_created_video_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_verified',
            new_name='is_approved',
        ),
    ]
